services:
  postgres:
    image: postgres:16
    ports:
      - 5431:5432
    entrypoint:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgressql/data

volumes:
  postgres_data:
